### ISSUE TITLE
Messages no longer working with placeholders

### ISSUE THREAD

**Issue by Hitosherizu** [PeachesMLG/CustomEnchants#1]
![messages](https://user-images.githubusercontent.com/6500498/43689402-167a9d36-98c8-11e8-84cc-0a9fdcbd071b.png)

**Comment by Hitosherizu** [comment]
Happens after the latest update, message.yml only change on our end is fixing the spelling mistake on "Received"

**Comment by PeachesMLG** [comment]
Sorry, this was to fix the lowwer case issue. try "%tier%" They are now case sensitive
