### ISSUE TITLE
[V17.4] All the enchantments

### ISSUE THREAD

**Issue by Acenox** [PeachesMLG/CustomEnchants#13]
Hello,

I think I know where the "bug" of the enchantments I have on my server comes from, because when a book is renamed on the config, it does not work anymore. Maybe I was wrong in the configuration, that's why I just posted it here: https://pastebin.com/bLsy9QQZ

But suddenly, all the famous books no longer work, while for example the enchantment "MultiShot" I did not rename it and it still works.

Best regards,

**Comment by PeachesMLG** [comment]
Thanks for reporting this, fixed in version 17.5, I also added an option to make the crystal item "glow" as if it is enchanted if you which to use this
