### ISSUE TITLE
Essentials interfering with custom enchanting plugin.

### ISSUE THREAD

**Issue by RoleModels** [PeachesMLG/CustomEnchants#14]
On my server, the custom enchants plugin is being overrided by essentials /ce command. 

My server is running spigot 1.8,8 and it running taco spigot & beer spigot & paper spigot.

**Comment by RoleModels** [comment]
It is also not giving me the item for the custom enchant.

**Comment by PeachesMLG** [comment]
talked to user, a skript plugin was causing compatability issues
