### ISSUE TITLE
customenchants tinker/tinkerer

### ISSUE THREAD

**Issue by samuel111111** [PeachesMLG/CustomEnchants#14]
when i input the commands it says an internal error occurred while executing the command this is the console error

issued server command: /tinkerer
01.06 13:54:23 [Server] ERROR null
01.06 13:54:23 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'tinkerer' in plugin CustomEnchants v17.1
01.06 13:54:23 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot_1.9.jar:git-Spigot-90839e6-8e5eab2]
01.06 13:54:23 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot_1.9.jar:git-Spigot-90839e6-8e5eab2]
01.06 13:54:23 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot_1.9.jar:git-Spigot-90839e6-8e5eab2]
01.06 13:54:23 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot_1.9.jar:git-Spigot-90839e6-8e5eab2]
01.06 13:54:23 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot_1.9.jar:git-Spigot-90839e6-8e5eab2]
01.06 13:54:23 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot_1.9.jar:git-Spigot-90839e6-8e5eab2]
01.06 13:54:23 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot_1.9.jar:git-Spigot-90839e6-8e5eab2]
01.06 13:54:23 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_1.9.jar:git-Spigot-90839e6-8e5eab2]
01.06 13:54:23 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
01.06 13:54:23 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
01.06 13:54:23 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot_1.9.jar:git-Spigot-90839e6-8e5eab2]
01.06 13:54:23 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot_1.9.jar:git-Spigot-90839e6-8e5eab2]
01.06 13:54:23 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_1.9.jar:git-Spigot-90839e6-8e5eab2]
01.06 13:54:23 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot_1.9.jar:git-Spigot-90839e6-8e5eab2]
01.06 13:54:23 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot_1.9.jar:git-Spigot-90839e6-8e5eab2]
01.06 13:54:23 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
01.06 13:54:23 [Server] INFO Caused by: java.lang.NullPointerException

**Comment by samuel111111** [comment]
also Enderforged dose not seam to work i just get partical effect same with stealth also i changed Xp levels to Vault  and it did not work

**Comment by PeachesMLG** [comment]
try updating to latest version
