### ISSUE TITLE
[V18.8] Enchantement Haste III

### ISSUE THREAD

**Issue by Acenox** [PeachesMLG/CustomEnchants#16]
Hello,

The enchantment "Haste III" does not work, indeed my players put it on a pick, but it does not give the effect. Yet "Haste II" gives the effect.

Best regards

**Comment by PeachesMLG** [comment]
all seems to be working for me, make sure HasteIII is enabled in Enabled.HasteIII and Maxpower.Haste is set to 3

**Comment by Acenox** [comment]
Oh yes, thanks, fixed :)
