### ISSUE TITLE
Internal Error on command /ce list

### ISSUE THREAD

**Issue by ProfCube** [PeachesMLG/CustomEnchants#17]
Hi I noticed that when I do /ce list it gives and internal error on the command but I made a skript that is a work around it if people want to use it. I made it so it list all the enchantments in a GUI format. If you feel like you want me to take it down please tell me. 
https://www.spigotmc.org/resources/enchantsgui-skript-extension.58904/

**Comment by PortGasMC** [comment]
I have the same problem when doing /ce list

**Comment by dabou0** [comment]
what version are u using ? your server version

**Comment by PortGasMC** [comment]
I'm using 1.12spigot latest build

**Comment by PeachesMLG** [comment]
are you updated to the latest version? also did you build it from github or purchase on spigot? as its working fine for me

**Comment by PortGasMC** [comment]
https://pastebin.com/gBN4FK5X
this error

**Comment by PeachesMLG** [comment]
ok. did you build it from github or did you buy it on spigot?

**Comment by PeachesMLG** [comment]
as its working fine for me

**Comment by PortGasMC** [comment]
it was buid by a paid developer 
now he scammed me, not to fix that error 
i dont have money to buy it on spigot 
so if a Little help Will be apreciate 
thanks

**Comment by PeachesMLG** [comment]
if you built it from github its either a problem with you building it or an issue i fixed. please either wait for version 2.0.0 to release or purchase the plugin on spigot
