### ISSUE TITLE
Infusion/Blazing Touch

### ISSUE THREAD

**Issue by Hitosherizu** [PeachesMLG/CustomEnchants#19]
Infusion and Blazingtouch no longer work with Silk Spawners, it destroys the spawner despite saying that it has been dropped/mined.

**Comment by PeachesMLG** [comment]
do you have "useblockbreakevent" set to true in the config.yml?

**Comment by Hitosherizu** [comment]
I do have block break events toggled on. Also is allowing users to break blocks protected by towny with infusion.

**Comment by PeachesMLG** [comment]
ok, SilkSpawners does not drop spawners if you are in gmc. Also you may be able to break blocks claimed by other plugins as you are opped. try removing all perms and deopping yourself then testing Infusion

**Comment by Hitosherizu** [comment]
The problems reported are by players, who are in survival and not opped.

**Comment by PeachesMLG** [comment]
try updating to the latest version? It works fine on my dev server
