### ISSUE TITLE
CE Purchasing 

### ISSUE THREAD

**Issue by arenmarsden** [PeachesMLG/CustomEnchants#3]
When people attempt to purchase a custom enchant, it errors in console "Unknown Enchant" for any enchant, nor can we spawn them in.

**Comment by arenmarsden** [comment]
This plugin is purchased off Spigot, the error in console is: https://pastebin.com/raw/kD6ztJDU (before updating to 16.0) After updating to 16.0 it says "Unknown Enchant" when they try to purchase a CE: https://pastebin.com/raw/V1Z55YhP

**Comment by PeachesMLG** [comment]
Sorry, I Tried this on my test server and everything worked fine, try deleting config.yml?

**Comment by PeachesMLG** [comment]
Sorry, I see my mistake, I will fix this now
