### ISSUE TITLE
[Latest] Bug with messages.yml

### ISSUE THREAD

**Issue by Acenox** [PeachesMLG/CustomEnchants#6]
Hello,

I finally switched to version 2.0 of the plugin, and I notice that there is a problem with the variables %Tier% and %Enchant% did this change? if so, can you give me the new variables? Or is it a bug?

Thank you!

Best regards,

**Comment by Acenox** [comment]
Okey, I just found by myself, do not put the capital letters %tier% and %enchant% but I leave the issue open, so that the problem is solved at the next update (because it remains still in the basic configuration).

**Comment by PeachesMLG** [comment]
yep, sorry. before i made the message turn into lowercase to make it so you could use %Tier% but thats removed now as people were complaining about not being able to capatalise messages
