### ISSUE TITLE
Request - Blast Enchant - Allowing Pickaxe to Make 3x3 mining

### ISSUE THREAD

**Issue by Vestle** [PeachesMLG/CustomEnchants#8]
Hi there! Im curious if it were possible to design a Blast enchant like CrazyEnchantments.
  Blast: 
    Name: 'Blast'
    MaxPower: 3
    Info:
      Name: Blast (I-III)
      Description:
        - '&7Breaks blocks in a 3 x level x 3 radius'
        - '&7depending on the power of the enchantment.'

        - 'Found in:'
        - ' - Legendary'
        - 'Enchantable Items: Pickaxes'
    Categories:
      - 'Legendary'

**Comment by PeachesMLG** [comment]
Its called Infusion

**Comment by Vestle** [comment]
My apologies. THank you for your help. I will now close!
