### ISSUE TITLE
[V17.3] All the enchantments

### ISSUE THREAD

**Issue by Acenox** [PeachesMLG/CustomEnchants#8]
Hello, 

Since this version, it is no longer possible to apply an enchantment with the books. There is no error in the console, but the menu does not open, as it usually opens to apply enchantment to the item or armor.

Best regards,

**Comment by PeachesMLG** [comment]
Whats the error in console?

**Comment by PeachesMLG** [comment]
sorry my mistake, ill look into it

**Comment by Acenox** [comment]
The problem is solved in version V17.4 thanks :)
