### ISSUE TITLE
[V17.4] Leader enchant

### ISSUE THREAD

**Issue by Acenox** [PeachesMLG/CustomEnchants#9]
Hello, 

I just saw that the enchantment "Leader" does not seem to work at home, do you need the latest version? because I use a rather old version, weird because in any case, the enchantment "Wings" works.

Best regards,

**Comment by PeachesMLG** [comment]
will look into it

**Comment by Acenox** [comment]
@PeachesMLG Have you any news?

**Comment by PeachesMLG** [comment]
sorry, i had my exams and stuff now that they have finished I will be fixing all these bugs, sorry

**Comment by Acenox** [comment]
@PeachesMLG  The problem is not solved on my server, I use a very old version of Faction and I guess it's because of this :/
